[package]
name = "crawler"
version = "0.1.0"
authors = ["Catamondium <30911915+Catamondium@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
reqwest = "0.9.19"
rand = "0.7.0"