[package]
name = "dedupdir"
version = "0.1.0"
authors = ["Catamondium <30911915+Catamondium@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
md5 = "0.7.0"